#!/usr/bin/env bash
# show dimains info


info () {
	record=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	ip=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
	echo "The subdomain $2 is a $record record and points to $ip"
}

if [ "$#" = 1 ]
then
    subs=("www" "lb-01" "web-01" "web-02")
    for name in "${subs[@]}"
    do
		info "$1" "$name"
    done
else
	info "$1" "$2"
fi
