#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages
# installing nginx the web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
