#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

cat /etc/nginx/sites-available/default > /etc/nginx/sites-enabled/default
echo "" | sudo status=none of=/run/nginx.pid
sudo service nginx restart
