#!/usr/bin/env bash
# Stops 4-to_infinity_and_beyond process.

if [ -n "$pid" ]; then
	# Use kill command to stop the process
	kill "$pid"
	echo "Process with PID $pid has been stopped."
else
	echo "Process '4-to_infinity_and_beyond' not found."
fi
