#!/usr/bin/env bash
# Stops the indefinite display of "To infinity and beyond" process without the use of the "kill" or "killall" command.

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
	kill -2 "$pid"
	echo "Process with PID $pid has been stopped."
else
	echo "Process '4-to_infinity_and_beyond' not found."
fi
