#!/usr/bin/env bash
# Function to handle SIGTERM signal

#!/usr/bin/env bash

# Function to handle SIGTERM signal
sigterm_handler() {
    echo "I am invincible!!!"
    exit 0
}

# Trap SIGTERM signal and call the handler function
trap 'sigterm_handler' SIGTERM

# Infinite loop displaying the message and sleeping for 2 seconds
while true; do
    echo "To infinity and beyond"
    sleep 2
done

