#!/usr/bin/env bash
# Displays the content of the file "/etc/passwd".
# Displays usernname.
# Displays user id.
# Displays Home directory path for the user.

file="/etc/passwd"

while IFS=: read -r username _ userid _ homedir _
do
	echo "Username: $username"
	echo "User ID: $userid"
	echo "Home Directory: $homedir"
done < "$file"
