#!/usr/bin/env bash
# Displays the visitor IP along with the HTTP status code from the Apache log file.
# Parses Apache log files in list format.
#   Displays the IP and HTTP status code.

awk '{print $1 " " $9}' apache-access.log
