#!/usr/bin/env bash
# Displays the visitor IP along with the HTTP status code from the Apache log file.

logfile="/var/log/apache2/access.log"

awk '{print $1, $9}' "$logfile" | sed 's/.*\[//;s/\].*//;s/"//g' | awk '{print $1, $NF}' | sed 's/\"//g' | awk '{print $1, $2}' | sort -u
