#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, and displays this data.

# Define the Apache log file path

logfile="/var/log/apache2/access.log"

# Use awk to group visitors IP and HTTP status code and count occurrences

awk '{count[$1" "$9]++} END {for (ipcode in count) {print count[ipcode], ipcode}}' "$logfile" | sort -nr | awk '{print $1, $3, $2}'
