#!/usr/bin/env bash
# Displays "Best School" 10 timess with the use of a while loop.
# At the 9th iteration, it displays "hi" before "Best School".

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
done
