#!/usr/bin/env bash
# Displays "Best School" 10 timess with the use of a while loop.
# At the 9th iteration, it displays "hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best Schoo"
	(( count++ ))
done
