#!/usr/bin/env bash
# fixing issues gotten from docker
# make the apache server return Hello Holberton when querrying the root

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
service apache2 start
